import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { MainLayout } from '../components/Layout';
import PrdouctItem from '../components/ProductItem';
import { IProduct } from '../models';
import { useGetProductsQuery } from '../redux/products/product.api';
import styles from '../styles/Index.module.scss';

// interface Props {
//   data: IProduct[];
// }

export default function Home() {
  const { data } = useGetProductsQuery(10);
  return (
    <MainLayout title="Main Page">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main className="maga">
        <div className={styles.products}>
          {data && data.map((obj: any) => <PrdouctItem key={obj.id} {...obj} />)}
        </div>
      </main>
    </MainLayout>
  );
}

// export const getServerSideProps: GetServerSideProps = async () => {
//   const res = await fetch('https://fakestoreapi.com/products/category/electronics');
//   const data = await res.json();
//   console.log(data);

//   return {
//     props: {
//       data,
//     },
//   };
// };
